---

spring:
  profiles: dev
  datasource:
#    url: jdbc:mysql://kmmwdvl9gxkn00qv:jtgxnrgznd4ikziq@z37udk8g6jiaqcbx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/ht7vcw1fdlysxgp8
    url: jdbc:mysql://localhost:3306/financialManagerAppDB
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 5000


---

spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
